on: [push, pull_request]

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]

    steps:
      - name: Checkout
        uses: actions/checkout@v3 # Updated to latest version

      - name: Setup node env
        uses: actions/setup-node@v3 # Ensuring the latest version is used
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install # Explicitly using 'install' for clarity

      - name: Generate
        run: yarn generate # Consistent with 'generate' script in package.json

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4 # Updated to latest version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
